apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aline-my
  namespace: aline-fargate-ns-my
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: bank-service-my
              servicePort: 8083