apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: aline-fargate-ns-my
  name: aline-ingress-my
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: aline-lbn-my
spec:
  rules:
    - host: my.dev.cloudsharks.name
      http:
        paths:
          - path: /users*
            pathType: Prefix
            backend:
              service:
                name: user-service-my
                port:
                  number: 8070
          - path: /login*
            pathType: Prefix
            backend:
              service:
                name: user-service-my
                port:
                  number: 8070
          - path: /applic*
            pathType: Prefix
            backend:
              service:
                name: underwriter-service-my
                port:
                  number: 8071
          - path: /members*
            pathType: Prefix
            backend:
              service:
                name: bank-service-my
                port:
                  number: 8083
          - path: /branch*
            pathType: Prefix
            backend:
              service:
                name: bank-service-my
                port:
                  number: 8083
          - path: /bank*
            pathType: Prefix
            backend:
              service:
                name: bank-service-my
                port:
                  number: 8083
          - path: /trans*
            pathType: Prefix
            backend:
              service:
                name: transaction-service-my
                port:
                  number: 8073
