apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deploy
  labels:
    app: bank-ms

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-ms
  template:
    metadata:
      labels:
        app: bank-ms
    spec:
      containers:
        - name: bank-ms
          image: myates7748/bank-ms:v1.0
          # resources:
          #   limits:
          #       memory: 256Mi
          #       cpu: 500m
          #   requests:
          #       memory: 126Mi
          #       cpu: 250m
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_PASSWORD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_USER
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: ENCRYPT_SECRET_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: JWT_SECRET_KEY
  
---

apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  type: NodePort
  selector:
    app: bank-ms
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30883
