apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    app: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: myates7748/aline-db:v1.0
          # resources:
          #   limits:
          #       memory: 256Mi
          #       cpu: 500m
          #   requests:
          #       memory: 126Mi
          #       cpu: 250m
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_PASSWORD 
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-persist-claim
  
---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
