apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deploy
  labels:
    app: admin-portal

spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
        - name: admin-portal
          image: myates7748/admin-portal:v1.0
          # resources:
          #   limits:
          #       memory: 256Mi
          #       cpu: 500m
          #   requests:
          #       memory: 126Mi
          #       cpu: 250m
          ports:
            - containerPort: 3000
          env:
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: ENCRYPT_SECRET_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: JWT_SECRET_KEY
  
---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: NodePort
  selector:
    app: admin-portal
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
