apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: gateway-ms

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-ms
  template:
    metadata:
      labels:
        app: gateway-ms
    spec:
      containers:
        - name: gateway-ms
          image: myates7748/aline-gateway:v1.1
          resources:
            limits:
                memory: 512Mi
                cpu: 500m
          ports:
            - containerPort: 8080
          env:
            - name: APP_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: aline-config-gw
                  key: APP_SERVICE_HOST
            - name: PORTAL_LANDING
              valueFrom:
                configMapKeyRef:
                  name: aline-config-gw
                  key: PORTAL_LANDING
            - name: PORTAL_DASHBOARD
              valueFrom:
                configMapKeyRef:
                  name: aline-config-gw
                  key: PORTAL_DASHBOARD
            - name: PORTAL_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: aline-config-gw
                  key: PORTAL_ADMIN
  
---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30880
