apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deploy
  labels:
    app: landing-portal

spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-portal
  template:
    metadata:
      labels:
        app: landing-portal
    spec:
      containers:
        - name: landing-portal
          image: myates7748/landing-portal:v1.0
          resources:
            limits:
                memory: 512Mi
                cpu: 500m
          ports:
            - containerPort: 3007
            
---

apiVersion: v1
kind: Service
metadata:
  name: landing-service
spec:
  type: NodePort
  selector:
    app: landing-portal
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
      nodePort: 30307
