- hosts: aws-jenkins
  become: true
  tasks:
    - name: Download Jenkins Release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import Jenkins Key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Update Yum
      yum:
        name: '*'
        state: latest
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
    - name: Reload Daemon
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Start Jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
