apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment-my
  namespace: aline-fargate-ns-my
  labels:
    app: transaction-ms-my

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: transaction-ms-my
  template:
    metadata:
      labels:
        app: transaction-ms-my
    spec:
      containers:
        - name: transaction-ms-my
          image: ${AWS_ID}.dkr.ecr.us-east-1.amazonaws.com/my-transaction-microservice:v1.0
          resources:
            limits:
                memory: 512Mi
                cpu: 500m
          ports:
            - containerPort: 8073
          envFrom:
            - configMapRef:
                name: eks-configmap
            - secretRef:
                name: eks-secret

---

apiVersion: v1
kind: Service
metadata:
  name: transaction-service-my
  namespace: aline-fargate-ns-my
  labels:
    app: transaction-ms-my
spec:
  selector:
    app: transaction-ms-my
  ports:
    - protocol: TCP
      port: 8073
      targetPort: 8073
      nodePort: 30873
