apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment-my
  namespace: aline-fargate-ns-my
  labels:
    app: user-ms-my

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-ms-my
  template:
    metadata:
      labels:
        app: user-ms-my
    spec:
      containers:
        - name: user-ms-my
          image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/my-user-microservice:v1.0
          resources:
            requests:
              memory: 0.5Gi
              cpu: 0.25vCPU
            limits:
              memory: 1Gi
              cpu: 0.5vCPU
          ports:
            - containerPort: 8070
          envFrom:
            - configMapRef:
                name: eks-configmap
            - secretRef:
                name: eks-secret
  
---

apiVersion: v1
kind: Service
metadata:
  name: user-service-my
  namespace: aline-fargate-ns-my
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  labels:
    app: user-ms-my
spec:
  type: LoadBalancer
  selector:
    app: user-ms-my
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30870
