- hosts: aws1
  remote_user: root
  become: true
  tasks:
    - name: Install Apache
      yum: name=httpd state=present
    - name: Start Apache
      service: name=httpd state=started
    - name: Download Jenkins Release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import Jenkins Key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Update Yum
      yum:
        name: '*'
        state: latest
    - name: Install Java
      yum:
        name: java-11-openjdk-devel
        state: present
    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
    - name: Reload Daemon
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Start Jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
# - hosts: localhost
#   tasks: 
#     - name: Provision Infrastructure
#       shell: |
#         # terraform commands
#     - name: Create Cluster
#       shell: |
#         # eks setup commands

