version: '3'

services:

  my-bank-ms:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/my-bank-microservice:v1.0
    container_name: my-bank-ms
    env_file:
      - dev_setup.env
    ports:
      - 8083:8083
    networks:
      - my_aline_nw

  my-transaction-ms:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/my-transaction-microservice:v1.0
    container_name: my-transaction-ms
    env_file:
      - dev_setup.env
    ports:
      - 8073:8073
    networks:
      - my_aline_nw

  my-underwriter-ms:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/my-underwriter-microservice:v1.0
    container_name: my-underwriter-ms
    env_file:
      - dev_setup.env
    ports:
      - 8071:8071
    networks:
      - my_aline_nw

  my-user-ms:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/my-user-microservice:v1.0
    container_name: my-user-ms
    env_file:
      - dev_setup.env
    ports:
      - 8070:8070
    networks:
      - my_aline_nw

networks:
  my_aline_nw:
    name: my-aline