apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user-ms

spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: user-ms
          image: myates7748/user-ms:v1.1
          resources:
            limits:
                memory: 512Mi
                cpu: 500m
          ports:
            - containerPort: 8070
          envFrom:
            - configMapRef:
                name: aline-config-ms
            - secretRef:
                name: aline-secret-ms
  
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-ms
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30870
