apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deploy
  labels:
    app: bank-ms

spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-ms
  template:
    metadata:
      labels:
        app: bank-ms
    spec:
      containers:
        - name: bank-ms
          image: myates7748/bank-ms:v1.1
          resources:
            limits:
                memory: 512Mi
                cpu: 500m
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: aline-config-ms
            - secretRef:
                name: aline-secret-ms

---

apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  type: NodePort
  selector:
    app: bank-ms
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30883
