apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-deploy
  labels:
    app: underwriter-ms

spec:
  replicas: 2
  selector:
    matchLabels:
      app: underwriter-ms
  template:
    metadata:
      labels:
        app: underwriter-ms
    spec:
      containers:
        - name: underwriter-ms
          image: myates7748/underwriter-ms:v1.1
          resources:
            limits:
                memory: 512Mi
                cpu: 500m
          ports:
            - containerPort: 8071
          envFrom:
            - configMapRef:
                name: aline-config-ms
            - secretRef:
                name: aline-secret-ms
  
---

apiVersion: v1
kind: Service
metadata:
  name: underwriter-service
spec:
  type: NodePort
  selector:
    app: underwriter-ms
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 30871
