- name: Ensure Maven and Java Dependency is Present
  hosts: temp
  become: true
  tasks:
    - name: Install Java for RedHat Systems
      apt:
        name: java-1.8.0-openjdk
        state: latest
      when: ansible_os_family == "Redhat"

    - name: Install Java Repo for Debian Systems
      apt_repository:
        name: ppa:openjdk-r/ppa
        state: present
      when: ansible_os_family == "Debian"
    - name: Install Java for Debian Systems
      apt:
        name: openjdk-8-jdk
        state: latest

    - name: Install Maven
      package:
        name: maven
        state: latest
