- name: Ensure Python is Installed and Updated
  hosts: temp
  become: true
  tasks:
    - name: Install Python
      package: 
        name: python3
        state: latest

    - name: Install pip
      package:
        name: python-pip
        state: latest
